### PR TITLE
Blank tiles at higher zoom levels

### PR DESCRIPTION
**Pull request by ehunter-usgs**
Always use the arcgis web service to serve map tiles.

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
Do we always want to use arcgis, or the composite (first 8 via eq, rest via arcgis) similar to the map/list?

**Comment by ehunter-usgs** [comment]
According to Eric, arcgis has stated that they can handle the load that we
will generate, so we should give it a shot.

On Tue, Jan 6, 2015 at 9:16 AM, Jeremy Fee <notifications@github.com> wrote:

> Do we always want to use arcgis, or the composite (first 8 via eq, rest
> via arcgis) similar to the map/list?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/usgs/earthquake-eventpages/pull/127#issuecomment-68887140>
> .
>



-- 
Thanks,
Eddie Hunter

**Comment by emartinez-usgs** [comment]
Using ArcGIS should be fine. We can back-track if this causes problems. Nonetheless, please use both "server.arcgisonline.com" and "services.arcgisonline.com"; in this way we can leverage multiple domains for parallel content downloads. This is supported in leaflet using the "{s}" and "subdomains" configurations.

**Comment by jmfee-usgs** [comment]
also part of #133

**Pull request closed without merging**
