### PR TITLE
Core module

### LINKED ISSUE #809: Create core module
... typically for services ...

### PR DESCRIPTION
**Pull request by jmfee-usgs**
Fixes #809

Refactor services to CoreModule, and make service BehaviorSubject's public.

@dslosky-usgs : I think this is what is required to import event page services into another project, and populate them from another service.

### CODE REVIEW

**Comment by emartinez-usgs** [comment]
Please rebase.

**Comment by emartinez-usgs** [comment]
... needs another rebase ... :(

**Comment by emartinez-usgs** [comment]
Like a broken record, but please rebase again.

**Comment by jmfee-usgs** [comment]
also like a broken record, I've rebased yet again.  This pr should be merged or deleted and re-implemented!

**Pull request merged**
