### PR TITLE
Shakemap legends

### LINKED ISSUE #925: Map for Shakemap module

### PR DESCRIPTION
**Pull request by dslosky-usgs**
Closes #925 

Adds the large legend below the intensity map (There might be a higher quality one out there, but I'm setting a max size on this one so it doesn't get blurry)

Adds a legend property to the overlay.layer for the interactive map (For some reason it's not added to the legend if the page is refreshed on the interactive map... Then removing and adding the layer again adds the legend)

increased test coverage for shakemapOverlays
Add alternate intensity JPEG for older events

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
This seems like a better quality and smaller file size for the large legend:
https://github.com/usgs/shakemap/blob/master/docs/_images/Figure_1_16_top.png , or I extracted this using illustrator as an alternative that is even smaller:




Rename to shakemap-intensity-legend.png
Could use a small legend name shakemap-intensity-legend-small.png

**Comment by jmfee-usgs** [comment]
Or this SVG may be even better
[shakemap-intensity-legend.svg.zip](https://github.com/usgs/earthquake-eventpages/files/1933152/shakemap-intensity-legend.svg.zip)

**Comment by emthompson-usgs** [comment]
I just want to check that you guys are aware that there are different versions of this scale for different events. @cbworden may want to comment.

**Comment by dslosky-usgs** [comment]
@jmfee-usgs the coloring for the SVG didn't quite work out; the instrumental intensity scale doesn't quite span the whole figure

**Comment by emthompson-usgs** [comment]
Yeah, this issue can be a bit of a headache. I think that you'll probably need to detect which conversion is used for the event and use that to select the correct legend. For example, compare the legends on these two shakemaps:
https://earthquake.usgs.gov/earthquakes/eventpage/nc71338066#shakemap
https://earthquake.usgs.gov/earthquakes/eventpage/us100075y8#shakemap
The key to selecting the correct one should be in `info.json['processing']['mi2pgm']`.

**Comment by dslosky-usgs** [comment]
Thanks @emthompson-usgs; do you know if these are the only two options?

**Comment by emthompson-usgs** [comment]
I believe that these are currently the only two options but @cbworden should confirm. This might be the kind of issue where we could/should come up with a better solution in case there are changes in the future. I'm going to go talk to Bruce/Mike about it and get back to you.

**Comment by jmfee-usgs** [comment]
@emthompson-usgs , @cbworden : this will likely need to be set as a product property on the shakemap product; rather than "buried" in the info.json

**Comment by dslosky-usgs** [comment]
@emthompson-usgs @jmfee-usgs; @cbworden emailed to say we should probably just use Worden et al for now, and come up with a better solution down the road.

**Pull request merged**
