### PR TITLE
Shakemap Intensity overlay

### LINKED ISSUE #1727: ShakeMap Module update
@wald-usgs @cbworden @emthompson-usgs
Let me know if I miss anything here...

- Replace intensity contours with raster image download/intensity_overlay.png
- TOGGLE raster image with contours
- Add a download link

### PR DESCRIPTION
**Pull request by dslosky-usgs**
closes #1727 

Adds shakemap-intensity image overlay
Uses the image overlay as default for the shakemap landing page and the interactive map
Backwards compatible with 'ii_overlay.png' from shakemap V3
Adds a download link... Download link will open the shakemap jpeg instead of the image overlay; I figure this is what users are looking for

### CODE REVIEW

**Comment by dslosky-usgs** [comment]
@ehunter-usgs I think this is ready to go... Let me know if you see any more issues!

**Comment by dslosky-usgs** [comment]
@jmfee-usgs I think it's probably better to use the map extents because a small event with an epicenter at -178 might not need to wrap, but a large event would!

**Comment by jmfee-usgs** [comment]
True, my main concern is that we calculate based on where the epicenter appears on the map; if the epicenter is at -178, the map extents should be centered around the epicenter and use negative longitudes...

**Comment by dslosky-usgs** [comment]
Agreed! Alright, I just pushed some changes up here, let me know if you had something else in mind

**Pull request merged**
