### PR TITLE
Usgs/earthquake eventpages#222

### PR DESCRIPTION
**Pull request by jdbrown-USGS**
fixes usgs/earthquake-eventpages#222
- Added Latitude and Longitude columns

fixes usgs/earthquake-eventpages#242
- Removed location column
- Added State, and zip columns

fixes usgs/earthquake-eventpages#221
- Added units to distance column

### CODE REVIEW

**Comment by emartinez-usgs** [comment]
Formatter functionality should probably be moved to the base/Formatter class. The `number` method in that class is a bit more robust than what is implemented here, and formatting should be consistent across modules.

**Comment by ehunter-usgs** [comment]
@emartinez-usgs should the base/Formatter be refactored to work more like base/ImpactUtil? instead of using prototypal inheritance?

**Comment by emartinez-usgs** [comment]
Prototypal inheritance is a separate issue. However, the base/Formatter class is using instance-level options `this._options`, so it can't be refactored to how the ImpactUtil works.

**Comment by jdbrown-USGS** [comment]
Modified formatter location class and removed the impact formatter class.

**Comment by jmfee-usgs** [comment]
Labels seem inappropriate for non-US events, for example us10003re5

Suggestions:
- rename `ZIP Name` to `Location`, make first column
- rename `State` to `Region`
- consider a single location column that can be formatted based on whether a zip/international, multiple columns for download only...

**Comment by jdbrown-USGS** [comment]
- Location is now one column containing City, State / Region, Zip, and Country. Locations can be sorted by each of these.

- Same Pull request

**Comment by jmfee-usgs** [comment]
Update the download format so city, state/region, zip, and country are all separate columns.
Alphabetize sort options.

**Comment by jdbrown-USGS** [comment]
- Updated download format.
- Alphabetized sort options.
- Location column in DYFI Responses table no longer wraps.

- Same Pull request

**Pull request merged**
