### PR TITLE
Issue 219

### PR DESCRIPTION
**Pull request by emartinez-usgs**
fixes usgs/earthquake-eventpages#219

Quite a deviation from the original issue. Summaries are now found on the module summary page only. These summaries to include location and time information for origin products as desired. Navigation links go directly to preferred information.

This change might also address (or make irrelevant) the following issues:
- #254
- #247

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
- executive summary origin row doesn't scroll on ie10
- clicking origin product from scientific summary page doesn't highlight the origin navigation item
- downloads shouldn't be on summary page
- downloads on detail page include all products, instead of current product

**Comment by jmfee-usgs** [comment]
- Will preferred event time be added just below page title?  Possibly (in addition) make origin table time value an abbreviation for full timestamp.

**Comment by jmfee-usgs** [comment]
- Why use `Array.prototype.push.apply(markup, [...])` instead of `markup.push(...)`?
  https://github.com/usgs/earthquake-eventpages/pull/272/files#diff-24785e7fc3992c2c52cb2a478561c4e9R255
- Is this line a typo (`scientifi`):
  https://github.com/usgs/earthquake-eventpages/pull/272/files#diff-cefc1e8fab1404c55ac22d413b30ed07R39

**Comment by emartinez-usgs** [comment]
Preferred event time is on the region info (default) page. Adjusted the event header is beyond the scope of this issue. Not sure how to fix non-scrolling summary on executive summary page. Seems okay as-is unless a fix is readily apparent.

**Comment by jmfee-usgs** [comment]
- `props`, `originAuthor`, `magnitudeAuthor`, `updateStamp` and `originProducts` seem unused?
https://github.com/emartinez-usgs/earthquake-eventpages/blob/issue-219/src/htdocs/modules/scientific/HypocenterPage.js#L303

**Pull request merged**
